// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/pvectgen/v1/service.proto

package pvectgenv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildEventType int32

const (
	BuildEventType_BUILD_EVENT_TYPE_UNSPECIFIED       BuildEventType = 0
	BuildEventType_BUILD_EVENT_TYPE_STEP_STARTED      BuildEventType = 1
	BuildEventType_BUILD_EVENT_TYPE_LOG               BuildEventType = 2
	BuildEventType_BUILD_EVENT_TYPE_STEP_COMPLETED    BuildEventType = 3
	BuildEventType_BUILD_EVENT_TYPE_STEP_FAILED       BuildEventType = 4
	BuildEventType_BUILD_EVENT_TYPE_DOWNLOAD_PROGRESS BuildEventType = 5
	BuildEventType_BUILD_EVENT_TYPE_BUILD_COMPLETED   BuildEventType = 6
	BuildEventType_BUILD_EVENT_TYPE_BUILD_FAILED      BuildEventType = 7
)

// Enum value maps for BuildEventType.
var (
	BuildEventType_name = map[int32]string{
		0: "BUILD_EVENT_TYPE_UNSPECIFIED",
		1: "BUILD_EVENT_TYPE_STEP_STARTED",
		2: "BUILD_EVENT_TYPE_LOG",
		3: "BUILD_EVENT_TYPE_STEP_COMPLETED",
		4: "BUILD_EVENT_TYPE_STEP_FAILED",
		5: "BUILD_EVENT_TYPE_DOWNLOAD_PROGRESS",
		6: "BUILD_EVENT_TYPE_BUILD_COMPLETED",
		7: "BUILD_EVENT_TYPE_BUILD_FAILED",
	}
	BuildEventType_value = map[string]int32{
		"BUILD_EVENT_TYPE_UNSPECIFIED":       0,
		"BUILD_EVENT_TYPE_STEP_STARTED":      1,
		"BUILD_EVENT_TYPE_LOG":               2,
		"BUILD_EVENT_TYPE_STEP_COMPLETED":    3,
		"BUILD_EVENT_TYPE_STEP_FAILED":       4,
		"BUILD_EVENT_TYPE_DOWNLOAD_PROGRESS": 5,
		"BUILD_EVENT_TYPE_BUILD_COMPLETED":   6,
		"BUILD_EVENT_TYPE_BUILD_FAILED":      7,
	}
)

func (x BuildEventType) Enum() *BuildEventType {
	p := new(BuildEventType)
	*p = x
	return p
}

func (x BuildEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_pvectgen_v1_service_proto_enumTypes[0].Descriptor()
}

func (BuildEventType) Type() protoreflect.EnumType {
	return &file_proto_pvectgen_v1_service_proto_enumTypes[0]
}

func (x BuildEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildEventType.Descriptor instead.
func (BuildEventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_pvectgen_v1_service_proto_rawDescGZIP(), []int{0}
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	ChecksumUrl   string                 `protobuf:"bytes,4,opt,name=checksum_url,json=checksumUrl,proto3" json:"checksum_url,omitempty"`
	Tags          string                 `protobuf:"bytes,5,opt,name=tags,proto3" json:"tags,omitempty"`
	Vendor        string                 `protobuf:"bytes,6,opt,name=vendor,proto3" json:"vendor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_proto_pvectgen_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pvectgen_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_proto_pvectgen_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *Image) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Image) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Image) GetChecksumUrl() string {
	if x != nil {
		return x.ChecksumUrl
	}
	return ""
}

func (x *Image) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *Image) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

type BuildStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildStep) Reset() {
	*x = BuildStep{}
	mi := &file_proto_pvectgen_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildStep) ProtoMessage() {}

func (x *BuildStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pvectgen_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildStep.ProtoReflect.Descriptor instead.
func (*BuildStep) Descriptor() ([]byte, []int) {
	return file_proto_pvectgen_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *BuildStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BuildStep) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type BuildRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BuildId           string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Image             *Image                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Steps             []*BuildStep           `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`
	CloudinitContent  []byte                 `protobuf:"bytes,4,opt,name=cloudinit_content,json=cloudinitContent,proto3" json:"cloudinit_content,omitempty"`
	CloudinitFilename string                 `protobuf:"bytes,5,opt,name=cloudinit_filename,json=cloudinitFilename,proto3" json:"cloudinit_filename,omitempty"`
	Options           map[string]string      `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BuildRequest) Reset() {
	*x = BuildRequest{}
	mi := &file_proto_pvectgen_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRequest) ProtoMessage() {}

func (x *BuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pvectgen_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRequest.ProtoReflect.Descriptor instead.
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return file_proto_pvectgen_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *BuildRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *BuildRequest) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *BuildRequest) GetSteps() []*BuildStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *BuildRequest) GetCloudinitContent() []byte {
	if x != nil {
		return x.CloudinitContent
	}
	return nil
}

func (x *BuildRequest) GetCloudinitFilename() string {
	if x != nil {
		return x.CloudinitFilename
	}
	return ""
}

func (x *BuildRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type BuildEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	StepName      string                 `protobuf:"bytes,2,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	Type          BuildEventType         `protobuf:"varint,3,opt,name=type,proto3,enum=pvectgen.v1.BuildEventType" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	StepIndex     int32                  `protobuf:"varint,5,opt,name=step_index,json=stepIndex,proto3" json:"step_index,omitempty"`
	Progress      float64                `protobuf:"fixed64,6,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildEvent) Reset() {
	*x = BuildEvent{}
	mi := &file_proto_pvectgen_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildEvent) ProtoMessage() {}

func (x *BuildEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pvectgen_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildEvent.ProtoReflect.Descriptor instead.
func (*BuildEvent) Descriptor() ([]byte, []int) {
	return file_proto_pvectgen_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *BuildEvent) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *BuildEvent) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *BuildEvent) GetType() BuildEventType {
	if x != nil {
		return x.Type
	}
	return BuildEventType_BUILD_EVENT_TYPE_UNSPECIFIED
}

func (x *BuildEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BuildEvent) GetStepIndex() int32 {
	if x != nil {
		return x.StepIndex
	}
	return 0
}

func (x *BuildEvent) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_pvectgen_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pvectgen_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_pvectgen_v1_service_proto_rawDescGZIP(), []int{4}
}

type HealthResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeName         string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Healthy          bool                   `protobuf:"varint,3,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ProxmoxVersion   string                 `protobuf:"bytes,4,opt,name=proxmox_version,json=proxmoxVersion,proto3" json:"proxmox_version,omitempty"`
	AvailableStorage []string               `protobuf:"bytes,5,rep,name=available_storage,json=availableStorage,proto3" json:"available_storage,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_pvectgen_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pvectgen_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_pvectgen_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetProxmoxVersion() string {
	if x != nil {
		return x.ProxmoxVersion
	}
	return ""
}

func (x *HealthResponse) GetAvailableStorage() []string {
	if x != nil {
		return x.AvailableStorage
	}
	return nil
}

type LaunchVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    int32                  `protobuf:"varint,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	NewVmId       int32                  `protobuf:"varint,2,opt,name=new_vm_id,json=newVmId,proto3" json:"new_vm_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Start         bool                   `protobuf:"varint,4,opt,name=start,proto3" json:"start,omitempty"`
	StartAtBoot   bool                   `protobuf:"varint,5,opt,name=start_at_boot,json=startAtBoot,proto3" json:"start_at_boot,omitempty"`
	IpConfig      string                 `protobuf:"bytes,6,opt,name=ip_config,json=ipConfig,proto3" json:"ip_config,omitempty"`
	Memory        int32                  `protobuf:"varint,7,opt,name=memory,proto3" json:"memory,omitempty"`
	Cores         int32                  `protobuf:"varint,8,opt,name=cores,proto3" json:"cores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchVMRequest) Reset() {
	*x = LaunchVMRequest{}
	mi := &file_proto_pvectgen_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchVMRequest) ProtoMessage() {}

func (x *LaunchVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pvectgen_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchVMRequest.ProtoReflect.Descriptor instead.
func (*LaunchVMRequest) Descriptor() ([]byte, []int) {
	return file_proto_pvectgen_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *LaunchVMRequest) GetTemplateId() int32 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *LaunchVMRequest) GetNewVmId() int32 {
	if x != nil {
		return x.NewVmId
	}
	return 0
}

func (x *LaunchVMRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LaunchVMRequest) GetStart() bool {
	if x != nil {
		return x.Start
	}
	return false
}

func (x *LaunchVMRequest) GetStartAtBoot() bool {
	if x != nil {
		return x.StartAtBoot
	}
	return false
}

func (x *LaunchVMRequest) GetIpConfig() string {
	if x != nil {
		return x.IpConfig
	}
	return ""
}

func (x *LaunchVMRequest) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *LaunchVMRequest) GetCores() int32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

type LaunchVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          int32                  `protobuf:"varint,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchVMResponse) Reset() {
	*x = LaunchVMResponse{}
	mi := &file_proto_pvectgen_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchVMResponse) ProtoMessage() {}

func (x *LaunchVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pvectgen_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchVMResponse.ProtoReflect.Descriptor instead.
func (*LaunchVMResponse) Descriptor() ([]byte, []int) {
	return file_proto_pvectgen_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *LaunchVMResponse) GetVmId() int32 {
	if x != nil {
		return x.VmId
	}
	return 0
}

func (x *LaunchVMResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LaunchVMResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_proto_pvectgen_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pvectgen_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_pvectgen_v1_service_proto_rawDescGZIP(), []int{8}
}

type TemplateInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          int32                  `protobuf:"varint,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tags          string                 `protobuf:"bytes,3,opt,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateInfo) Reset() {
	*x = TemplateInfo{}
	mi := &file_proto_pvectgen_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateInfo) ProtoMessage() {}

func (x *TemplateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pvectgen_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateInfo.ProtoReflect.Descriptor instead.
func (*TemplateInfo) Descriptor() ([]byte, []int) {
	return file_proto_pvectgen_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *TemplateInfo) GetVmId() int32 {
	if x != nil {
		return x.VmId
	}
	return 0
}

func (x *TemplateInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateInfo) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

type ListTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*TemplateInfo        `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_proto_pvectgen_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pvectgen_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_pvectgen_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListTemplatesResponse) GetTemplates() []*TemplateInfo {
	if x != nil {
		return x.Templates
	}
	return nil
}

var File_proto_pvectgen_v1_service_proto protoreflect.FileDescriptor

const file_proto_pvectgen_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/pvectgen/v1/service.proto\x12\vpvectgen.v1\"\x8c\x01\n" +
	"\x05Image\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12!\n" +
	"\fchecksum_url\x18\x04 \x01(\tR\vchecksumUrl\x12\x12\n" +
	"\x04tags\x18\x05 \x01(\tR\x04tags\x12\x16\n" +
	"\x06vendor\x18\x06 \x01(\tR\x06vendor\"9\n" +
	"\tBuildStep\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\"\xdb\x02\n" +
	"\fBuildRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12(\n" +
	"\x05image\x18\x02 \x01(\v2\x12.pvectgen.v1.ImageR\x05image\x12,\n" +
	"\x05steps\x18\x03 \x03(\v2\x16.pvectgen.v1.BuildStepR\x05steps\x12+\n" +
	"\x11cloudinit_content\x18\x04 \x01(\fR\x10cloudinitContent\x12-\n" +
	"\x12cloudinit_filename\x18\x05 \x01(\tR\x11cloudinitFilename\x12@\n" +
	"\aoptions\x18\x06 \x03(\v2&.pvectgen.v1.BuildRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xca\x01\n" +
	"\n" +
	"BuildEvent\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12\x1b\n" +
	"\tstep_name\x18\x02 \x01(\tR\bstepName\x12/\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1b.pvectgen.v1.BuildEventTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"step_index\x18\x05 \x01(\x05R\tstepIndex\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\x01R\bprogress\"\x0f\n" +
	"\rHealthRequest\"\xb7\x01\n" +
	"\x0eHealthResponse\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\ahealthy\x18\x03 \x01(\bR\ahealthy\x12'\n" +
	"\x0fproxmox_version\x18\x04 \x01(\tR\x0eproxmoxVersion\x12+\n" +
	"\x11available_storage\x18\x05 \x03(\tR\x10availableStorage\"\xe7\x01\n" +
	"\x0fLaunchVMRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\x05R\n" +
	"templateId\x12\x1a\n" +
	"\tnew_vm_id\x18\x02 \x01(\x05R\anewVmId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05start\x18\x04 \x01(\bR\x05start\x12\"\n" +
	"\rstart_at_boot\x18\x05 \x01(\bR\vstartAtBoot\x12\x1b\n" +
	"\tip_config\x18\x06 \x01(\tR\bipConfig\x12\x16\n" +
	"\x06memory\x18\a \x01(\x05R\x06memory\x12\x14\n" +
	"\x05cores\x18\b \x01(\x05R\x05cores\"[\n" +
	"\x10LaunchVMResponse\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\x05R\x04vmId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x16\n" +
	"\x14ListTemplatesRequest\"K\n" +
	"\fTemplateInfo\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\x05R\x04vmId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04tags\x18\x03 \x01(\tR\x04tags\"P\n" +
	"\x15ListTemplatesResponse\x127\n" +
	"\ttemplates\x18\x01 \x03(\v2\x19.pvectgen.v1.TemplateInfoR\ttemplates*\xa7\x02\n" +
	"\x0eBuildEventType\x12 \n" +
	"\x1cBUILD_EVENT_TYPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dBUILD_EVENT_TYPE_STEP_STARTED\x10\x01\x12\x18\n" +
	"\x14BUILD_EVENT_TYPE_LOG\x10\x02\x12#\n" +
	"\x1fBUILD_EVENT_TYPE_STEP_COMPLETED\x10\x03\x12 \n" +
	"\x1cBUILD_EVENT_TYPE_STEP_FAILED\x10\x04\x12&\n" +
	"\"BUILD_EVENT_TYPE_DOWNLOAD_PROGRESS\x10\x05\x12$\n" +
	" BUILD_EVENT_TYPE_BUILD_COMPLETED\x10\x06\x12!\n" +
	"\x1dBUILD_EVENT_TYPE_BUILD_FAILED\x10\a2\xb2\x02\n" +
	"\rMinionService\x12=\n" +
	"\x05Build\x12\x19.pvectgen.v1.BuildRequest\x1a\x17.pvectgen.v1.BuildEvent0\x01\x12A\n" +
	"\x06Health\x12\x1a.pvectgen.v1.HealthRequest\x1a\x1b.pvectgen.v1.HealthResponse\x12G\n" +
	"\bLaunchVM\x12\x1c.pvectgen.v1.LaunchVMRequest\x1a\x1d.pvectgen.v1.LaunchVMResponse\x12V\n" +
	"\rListTemplates\x12!.pvectgen.v1.ListTemplatesRequest\x1a\".pvectgen.v1.ListTemplatesResponseB;Z9github.com/aloks98/pve-ctgen/proto/pvectgen/v1;pvectgenv1b\x06proto3"

var (
	file_proto_pvectgen_v1_service_proto_rawDescOnce sync.Once
	file_proto_pvectgen_v1_service_proto_rawDescData []byte
)

func file_proto_pvectgen_v1_service_proto_rawDescGZIP() []byte {
	file_proto_pvectgen_v1_service_proto_rawDescOnce.Do(func() {
		file_proto_pvectgen_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pvectgen_v1_service_proto_rawDesc), len(file_proto_pvectgen_v1_service_proto_rawDesc)))
	})
	return file_proto_pvectgen_v1_service_proto_rawDescData
}

var file_proto_pvectgen_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_pvectgen_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_pvectgen_v1_service_proto_goTypes = []any{
	(BuildEventType)(0),           // 0: pvectgen.v1.BuildEventType
	(*Image)(nil),                 // 1: pvectgen.v1.Image
	(*BuildStep)(nil),             // 2: pvectgen.v1.BuildStep
	(*BuildRequest)(nil),          // 3: pvectgen.v1.BuildRequest
	(*BuildEvent)(nil),            // 4: pvectgen.v1.BuildEvent
	(*HealthRequest)(nil),         // 5: pvectgen.v1.HealthRequest
	(*HealthResponse)(nil),        // 6: pvectgen.v1.HealthResponse
	(*LaunchVMRequest)(nil),       // 7: pvectgen.v1.LaunchVMRequest
	(*LaunchVMResponse)(nil),      // 8: pvectgen.v1.LaunchVMResponse
	(*ListTemplatesRequest)(nil),  // 9: pvectgen.v1.ListTemplatesRequest
	(*TemplateInfo)(nil),          // 10: pvectgen.v1.TemplateInfo
	(*ListTemplatesResponse)(nil), // 11: pvectgen.v1.ListTemplatesResponse
	nil,                           // 12: pvectgen.v1.BuildRequest.OptionsEntry
}
var file_proto_pvectgen_v1_service_proto_depIdxs = []int32{
	1,  // 0: pvectgen.v1.BuildRequest.image:type_name -> pvectgen.v1.Image
	2,  // 1: pvectgen.v1.BuildRequest.steps:type_name -> pvectgen.v1.BuildStep
	12, // 2: pvectgen.v1.BuildRequest.options:type_name -> pvectgen.v1.BuildRequest.OptionsEntry
	0,  // 3: pvectgen.v1.BuildEvent.type:type_name -> pvectgen.v1.BuildEventType
	10, // 4: pvectgen.v1.ListTemplatesResponse.templates:type_name -> pvectgen.v1.TemplateInfo
	3,  // 5: pvectgen.v1.MinionService.Build:input_type -> pvectgen.v1.BuildRequest
	5,  // 6: pvectgen.v1.MinionService.Health:input_type -> pvectgen.v1.HealthRequest
	7,  // 7: pvectgen.v1.MinionService.LaunchVM:input_type -> pvectgen.v1.LaunchVMRequest
	9,  // 8: pvectgen.v1.MinionService.ListTemplates:input_type -> pvectgen.v1.ListTemplatesRequest
	4,  // 9: pvectgen.v1.MinionService.Build:output_type -> pvectgen.v1.BuildEvent
	6,  // 10: pvectgen.v1.MinionService.Health:output_type -> pvectgen.v1.HealthResponse
	8,  // 11: pvectgen.v1.MinionService.LaunchVM:output_type -> pvectgen.v1.LaunchVMResponse
	11, // 12: pvectgen.v1.MinionService.ListTemplates:output_type -> pvectgen.v1.ListTemplatesResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_pvectgen_v1_service_proto_init() }
func file_proto_pvectgen_v1_service_proto_init() {
	if File_proto_pvectgen_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pvectgen_v1_service_proto_rawDesc), len(file_proto_pvectgen_v1_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pvectgen_v1_service_proto_goTypes,
		DependencyIndexes: file_proto_pvectgen_v1_service_proto_depIdxs,
		EnumInfos:         file_proto_pvectgen_v1_service_proto_enumTypes,
		MessageInfos:      file_proto_pvectgen_v1_service_proto_msgTypes,
	}.Build()
	File_proto_pvectgen_v1_service_proto = out.File
	file_proto_pvectgen_v1_service_proto_goTypes = nil
	file_proto_pvectgen_v1_service_proto_depIdxs = nil
}
